### ISSUE TITLE
JenkinsFile doesn't show up as a OCP pipeline

### ISSUE THREAD

**Issue by alberttwong** [redhat-cop/spring-rest#19]
I just ran this using the RH OpenJDK S2I image and it just shows up as a regular build and not a pipeline build.  Thoughts?

**Comment by alberttwong** [comment]
Ahh.. I think I understand now.   This JenkinsFile is to be used with https://github.com/redhat-cop/container-pipelines/tree/master/basic-spring-boot.  It wasn't designed a standalone spin up jenkins to run through a set of Jenkins tasks.

**Comment by sherl0cks** [comment]
You need a build config with the pipeline strategy for this to show up in OCP as a pipeline. https://docs.openshift.com/container-platform/3.11/dev_guide/openshift_pipeline.html#jenkins-pipeline-strategy

The relevant code in quickstarts: https://github.com/redhat-cop/container-pipelines/blob/master/basic-spring-boot/.openshift/templates/build.yml#L40
