### ISSUE TITLE
Consider Using Snowdrop Boosters

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/spring-rest#21]
Instead of maintaining our own repo, we should consider collaborating with the Red Hat Spring team under the snowdrop org. Here is an example: https://github.com/snowdrop/spring-boot-http-booster

**Comment by garethahealy** [comment]
latest @ https://github.com/snowdrop/rest-http-example/tree/sb-2.2.x

**Comment by garethahealy** [comment]
stale, project either needs a big update or archiving since SB3 is out now.
